### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#146]
In the genattrib.py, the tool provides the following error when user forget to provide the "component_list" parameter:

Error:

```
Traceback (most recent call last):
  File "genattrib.py", line 293, in <module>
    main(parser, options, args)
  File "genattrib.py", line 216, in main
    f.write(attrib_str)
TypeError: expected a character buffer object
```

The above error doesn't give any information about the missing argument.
The tool should be able to catch that and give a better error message.

**Comment by chinyeungli** [comment]
This error is something else. This is not related to the input parameteres.
