### ISSUE TITLE
Better error message for invalid template_location

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#147]
We have the following errors when the template_location is not found:

Traceback (most recent call last):
  File "genattrib.py", line 293, in <module>
    main(parser, options, args)
  File "genattrib.py", line 216, in main
    f.write(attrib_str)
TypeError: expected a character buffer object

The error message needs to be improved to tell the exact problem.

**Comment by chinyeungli** [comment]
Fixed by add the following code in the genattrib.py

```
if not exists(template_location):
    print('The defined template location does not exist.')
    parser.print_help()
    sys.exit(errno.EINVAL)
```
