### ISSUE TITLE
Incorrect message regarding Jinja2 installation

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-toolkit#149]
If I run genattrib.py with Python 2.7.5 I get the following error and message:

python genattrib.py --overwrite --template_location=../template_HTML.html  /about-code-tool-develop/about_code_tool/project/ out.html /about-code-tool-develop/about_code_tool/project-filter-about.csv 
The Jinja2 templating library is required to generate attribution texts. You can install it by running:"configure"
Traceback (most recent call last):
  File "genattrib.py", line 293, in <module>
    main(parser, options, args)
  File "genattrib.py", line 216, in main
    f.write(attrib_str)
TypeError: expected a character buffer object

Aside from the TypeError, I am getting a message saying Jinja2 is not installed however if I run:
pip install jinja2
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages (from jinja2)
Cleaning up...

Jinja2 is installed but is pointing to the python 2.6 site-package location. The message should be changed to recognize that Jinja2 is installed but not for the version of python that is being used to run the tool.

**Comment by jdaguil** [comment]
The is not an issue if you run source ./configure which is stated in the README
