### ISSUE TITLE
Catch the invalid api_url

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#161]
Although we already have code to catch the 404 error, some users get the following message when they actually have an invalid api_url

Traceback (most recent call last):
  File "genabout.py", line 940, in <module>
    main(parser, options, args)
  File "genabout.py", line 856, in main
    dje_license_dict)
  File "genabout.py", line 415, in get_dje_license_list
    license_output_list.append(self.gen_license_list(line))
  File "genabout.py", line 561, in gen_license_list
    dje_license_name = line['dje_license_name']
KeyError: 'dje_license_name'

(This user resolve the issue by changing the https:// to http://)

**Comment by chinyeungli** [comment]
the error, perhaps, was unable to establish secure connection -- maybe that's not a 404

**Comment by chinyeungli** [comment]
Possible

497 HTTP to HTTPS (Nginx)
Nginx internal code used for the plain HTTP requests that are sent to HTTPS port to distinguish it from 4XX in a log and an error page redirection.
