### ISSUE TITLE
Windows installation issue for v7.0.0 through v7.2.0

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-toolkit#545]
The configure step fails for v7.0.0, v7.0.1, v7.0.2, v71.0 and v7.2.0 with the following error (this example is for  v7.0.0, but the error is similar for the others). I was using the standard Windows 10 Command Prompt with Python 3.8.10:
```
created virtual environment CPython3.8.10.final.0-64 in 8387ms
  creator CPython3Windows(dest=C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv, clear=False, no_vcs_ignore=True, global=False)
  seeder PipInvoke(download=False, pip=embed, setuptools=embed, wheel=embed)
    added seed packages: pip==23.2.1, setuptools==68.2.0, wheel==0.41.2
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Looking in links: c:\ABOUTCODE\aboutcode-toolkit-7.0.0\\thirdparty, https://thirdparty.aboutcode.org/pypi
Obtaining file:///C:/ABOUTCODE/aboutcode-toolkit-7.0.0
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\build_meta.py", line 473, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\_virtualenv.py", line 23, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\dist.py", line 661, in parse_config_files
          setupcfg.parse_configuration(
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\config\setupcfg.py", line 177, in parse_configuration
          options.parse()
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\config\setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\config\setupcfg.py", line 475, in parse_section
          self[name] = value
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\config\setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\_vendor\packaging\specifiers.py", line 714, in __init__
          parsed.add(Specifier(specifier))
        File "C:\ABOUTCODE\aboutcode-toolkit-7.0.0\venv\lib\site-packages\setuptools\_vendor\packaging\specifiers.py", line 245, in __init__
          raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
      setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=3.6.*'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Junction created for C:\ABOUTCODE\aboutcode-toolkit-7.0.0\\venv\bin <<===>> C:\ABOUTCODE\aboutcode-toolkit-7.0.0\\venv\Scripts
```

**Comment by chinyeungli** [comment]
This is fixed in https://github.com/nexB/aboutcode-toolkit/commit/cf76b2685ec8255bd49dcf4c9e0b355a46cb693b
